<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_pengesyoran</name>
   <tag></tag>
   <elementGuidId>7a43b57a-807b-476c-8895-79a7fba4d7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_myworkbasket_WAR_skssrbenefitportlet_INSTANCE_BABG2pr5LGfB_recommendationType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
