<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textarea_catatan</name>
   <tag></tag>
   <elementGuidId>30e6bb42-671b-422e-9d0a-234cb401b0c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_myworkbasket_WAR_skssrbenefitportlet_INSTANCE_BABG2pr5LGfB_recommendRemarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
